---
- name: Create Consul service definition
  include_role:
    name: consul-service
  vars:
    consul_config_name: '{{ ergo_service_name }}'
    consul_services:
      - id:   '{{ ergo_service_name }}'
        name: '{{ ergo_service_name }}'
        tags: ['irc', 'ergo']
        port: '{{ ergo_cont_text_port }}'
        checks:
          - id:   '{{ ergo_service_name }}-health'
            name: 'Ergo IRC Server Healthcheck'
            type: 'tcp'
            tcp: 'localhost:{{ ergo_cont_text_port }}'
