---
- name: Create compose file
  template:
    src:   'docker-compose.yml.j2'
    dest:  '{{ ergo_compose_file }}'
    owner: 'dockremap'
    group: 'docker'
    mode:  '0o640'

- name: Create containers
  community.docker.docker_compose_v2:
    project_src: '{{ ergo_service_path }}'
    state:       '{{ compose_state }}'
    recreate:    '{{ compose_recreate | default("auto") | replace("smart", "auto") }}'
    pull:        'always'

- name: Restart containers
  community.docker.docker_compose_v2:
    project_src: '{{ ergo_service_path }}'
    state:       'restarted'
  when:
    - compose_state == 'present'
    - ergo_config.changed or compose_restart | bool
